### ISSUE TITLE
Work with gulp

### ISSUE THREAD

**Issue by samskiter** [kevinrenskers/raml2md#11]
Hi, is there any chance you could make this work easily with gulp (as per the raml2html project) or provide an example on how to do it? Thanks!

**Comment by kevinrenskers** [comment]
Sorry, I don't use Gulp with either this or raml2html. There's a third party [gulp-raml2html](https://www.npmjs.org/package/gulp-raml2html) project you might want to look at for inspiration and somebody figured out how to directly use it from Gulp without a plugin: https://gist.github.com/iki/784ddd5ab33c1e1b726b. Maybe you can reuse some of that for raml2md.
