### ISSUE TITLE
no templatePath option

### ISSUE THREAD

**Issue by bpytlik** [kevinrenskers/raml2md#8]
raml2html has the very useful -p option, but raml2md doesn't seem to offer that option. Is that something that could get added in the future?

**Comment by kevinrenskers** [comment]
Yep, makes sense to add it. If you want to submit a pull request with this change that would be very welcome as well :)

**Comment by kevinrenskers** [comment]
Just FYI this option has been removed again in raml2md 2.3.0 which was just released. It's not needed since relative templates now work properly in Nunjucks.
