### ISSUE TITLE
Default template is incomplete

### ISSUE THREAD

**Issue by Batlan** [kevinrenskers/raml2md#9]
Hi Kevin,
I've started using RAML and find your raml2html converter very useful.

But as I would like to release a html or pdf documentation based on markdown and RAML documents, I started using raml2md and then create the overall document using pandoc.

Unfortunalty the default raml2md document isn't complete. Do you intend to complete this template ? Or what is the recommended way to get a markdown document from RAML?

**Comment by kevinrenskers** [comment]
I never intended the markdown version to render every single possible RAML value. It's more for readme's and stuff, thus very very basic. A list of resources and methods, descriptions, not much more then that.

If you want to add more things, you can always supply your own template.
